sudo: false

language: python

python:
    - "3.6"

addons:
    apt:
        packages:
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra

install:
    - pip install ads

script:
    - python get_pubs.py
    - python write_tex.py
    - git diff
    - make

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
        cd $TRAVIS_BUILD_DIR

        # Update the main repo
        git checkout $TRAVIS_BRANCH
        git add pubs.json pubs_ref.tex pubs_select.tex pubs_summary.tex pubs_unref.tex
        git -c user.name='travis' -c user.email='travis' commit -m "updating pubs [ci skip]"
        git push https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH

        # Update the PDF
        git checkout --orphan $TRAVIS_BRANCH-pdf
        git rm -rf .
        git add -f cv_pubs.pdf cv.pdf pubs.pdf
        git -c user.name='travis' -c user.email='travis' commit -m "current pdf"
        git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    fi

