name: Auto update

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          conda install pandoc
          python -m pip install ads
      - name: Update publication list
        run: make
        env:
          ADS_DEV_KEY: ${{secrets.ADS_DEV_KEY}}
          GITHUB_API_KEY: ${{secrets.GITHUB_TOKEN}}
      - name: Push updated data files
        continue-on-error: true
        run: |
          git add .
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "updating data"
          git push https://github.com/$GITHUB_REPOSITORY
      - name: Compile
        uses: docker://texlive/texlive:latest
        with:
          args: make tex
      - uses: dfm/force-push-branch-action@v1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: "-pdf"
          commit-message: "updating pdfs"
          path: "tex/*.pdf"
